-- =====================================================================
-- daizu — SCHEMA-SYNC.sql
-- =====================================================================
-- WHAT THIS IS
--   A faithful, idempotent reproduction of the CURRENT LIVE schema for
--   daizu's tables in the shared Supabase project "Kura"
--   (project_id: lrbmtcyhqzuyczovajnj).
--
--   Generated by introspecting the live Kura database on 2026-07-18.
--
-- WHY IT EXISTS
--   Schema changes were made directly in the Supabase SQL Editor over time
--   and were never written back into this repo. This file closes that gap:
--   it is what you run to recreate daizu's database from scratch.
--
-- ⚠️  supabase/schema.sql AND supabase/migration_bar.sql ARE OUTDATED —
--     DO NOT USE THEM FOR A FRESH DEPLOY. They create unprefixed tables
--     named `orders`, `favorites`, and `out_of_stock`. Those tables were
--     renamed live to `daizu_orders`, `daizu_favorites`, and
--     `daizu_out_of_stock` (Kura is a shared project; every app uses a
--     table prefix). Every API route in this repo queries the `daizu_`
--     names. The unprefixed tables do not exist in the live database.
--     Those files also predate the `mixer` and `subcategory` columns.
--     They are retained only as historical record; THIS FILE reflects
--     reality.
--
-- PROPERTIES
--   * Additive only. No DROP TABLE, no DROP COLUMN, no data changes.
--   * Fully idempotent — safe to run repeatedly. Against the existing live
--     database it is a complete no-op.
--   * Schema only. Contains no seed data and no user data.
--   * Statements are ordered to satisfy dependencies (sequences before the
--     tables that consume them). There are no foreign keys between daizu
--     tables — the three tables are independent.
--
-- NOTE ON LEGACY IDENTIFIER NAMES
--   The rename was a plain ALTER TABLE ... RENAME, which does NOT rename a
--   table's sequences, constraints, or indexes. So live still carries the
--   pre-rename names: sequence `orders_id_seq`, constraint
--   `favorites_temp_check`, index `orders_status_idx`, and so on. Only the
--   newer subcategory checks carry `daizu_` prefixes. This file reproduces
--   those exact names so it is a true no-op against live. They are cosmetic;
--   nothing in the app references them.
--
-- NOTE ON RLS
--   All three tables have RLS enabled with SELECT-only public policies and
--   NO insert/update/delete policies. Public writes are impossible by
--   design — every write path goes through a Next API route using the
--   service-role key, which bypasses RLS. Do not add write policies.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. SEQUENCES
--    Created explicitly (rather than via bigserial) to preserve the
--    legacy names that live still uses.
-- ---------------------------------------------------------------------

create sequence if not exists public.orders_id_seq       as bigint;
create sequence if not exists public.favorites_id_seq    as bigint;
create sequence if not exists public.out_of_stock_id_seq as bigint;


-- ---------------------------------------------------------------------
-- 2. TABLE: daizu_orders
--    Every order placed — cafe and bar alike. One table, two shapes:
--    coffee fields are null/empty for bar orders and vice versa.
-- ---------------------------------------------------------------------

create table if not exists public.daizu_orders (
  id               bigint      not null default nextval('public.orders_id_seq'),
  customer         text        not null default 'Dez',
  drink            text        not null,
  temp             text,
  milk             text,
  syrups           text[]      not null default '{}',
  sweetness        text                 default 'normal',
  extras           text[]      not null default '{}',
  notes            text                 default '',
  status           text        not null default 'received',
  ready_phrase_jp  text,
  ready_phrase_en  text,
  created_at       timestamptz not null default now(),
  ready_at         timestamptz,
  category         text        not null default 'cafe',
  strength         text,
  quantity         integer     not null default 1,
  spirit           text,
  mixer            text,
  subcategory      text,
  constraint orders_pkey primary key (id)
);

alter sequence public.orders_id_seq owned by public.daizu_orders.id;


-- ---------------------------------------------------------------------
-- 3. TABLE: daizu_favorites
--    Saved "usuals" that can be re-ordered with one tap.
-- ---------------------------------------------------------------------

create table if not exists public.daizu_favorites (
  id           bigint      not null default nextval('public.favorites_id_seq'),
  label        text        not null,
  drink        text        not null,
  temp         text,
  milk         text,
  syrups       text[]      not null default '{}',
  sweetness    text                 default 'normal',
  extras       text[]      not null default '{}',
  notes        text                 default '',
  customer     text                 default 'Dez',
  created_at   timestamptz not null default now(),
  category     text        not null default 'cafe',
  strength     text,
  quantity     integer     not null default 1,
  spirit       text,
  mixer        text,
  subcategory  text,
  constraint favorites_pkey primary key (id)
);

alter sequence public.favorites_id_seq owned by public.daizu_favorites.id;


-- ---------------------------------------------------------------------
-- 4. TABLE: daizu_out_of_stock
--    (category, item_id) pairs the barista has hidden from the menu.
--    POST /api/out-of-stock is a toggle: delete-if-exists, else insert.
-- ---------------------------------------------------------------------

create table if not exists public.daizu_out_of_stock (
  id        bigint not null default nextval('public.out_of_stock_id_seq'),
  category  text   not null,
  item_id   text   not null,
  constraint out_of_stock_pkey primary key (id),
  constraint out_of_stock_category_item_id_key unique (category, item_id)
);

alter sequence public.out_of_stock_id_seq owned by public.daizu_out_of_stock.id;


-- ---------------------------------------------------------------------
-- 5. COLUMNS (idempotent top-up for pre-existing tables)
--    Notably `mixer` and `subcategory` exist live but appear in NO
--    committed SQL file in this repo — they were added straight in the
--    SQL Editor. They are the substantive (non-rename) drift.
--    Columns are added without NOT NULL here so this is safe against
--    populated tables; NOT NULL is applied in section 7.
-- ---------------------------------------------------------------------

-- daizu_orders
alter table public.daizu_orders add column if not exists customer        text default 'Dez';
alter table public.daizu_orders add column if not exists drink           text;
alter table public.daizu_orders add column if not exists temp            text;
alter table public.daizu_orders add column if not exists milk            text;
alter table public.daizu_orders add column if not exists syrups          text[] default '{}';
alter table public.daizu_orders add column if not exists sweetness       text default 'normal';
alter table public.daizu_orders add column if not exists extras          text[] default '{}';
alter table public.daizu_orders add column if not exists notes           text default '';
alter table public.daizu_orders add column if not exists status          text default 'received';
alter table public.daizu_orders add column if not exists ready_phrase_jp text;
alter table public.daizu_orders add column if not exists ready_phrase_en text;
alter table public.daizu_orders add column if not exists created_at      timestamptz default now();
alter table public.daizu_orders add column if not exists ready_at        timestamptz;
alter table public.daizu_orders add column if not exists category        text default 'cafe';
alter table public.daizu_orders add column if not exists strength        text;
alter table public.daizu_orders add column if not exists quantity        integer default 1;
alter table public.daizu_orders add column if not exists spirit          text;
alter table public.daizu_orders add column if not exists mixer           text;
alter table public.daizu_orders add column if not exists subcategory     text;

-- daizu_favorites
alter table public.daizu_favorites add column if not exists label       text;
alter table public.daizu_favorites add column if not exists drink       text;
alter table public.daizu_favorites add column if not exists temp        text;
alter table public.daizu_favorites add column if not exists milk        text;
alter table public.daizu_favorites add column if not exists syrups      text[] default '{}';
alter table public.daizu_favorites add column if not exists sweetness   text default 'normal';
alter table public.daizu_favorites add column if not exists extras      text[] default '{}';
alter table public.daizu_favorites add column if not exists notes       text default '';
alter table public.daizu_favorites add column if not exists customer    text default 'Dez';
alter table public.daizu_favorites add column if not exists created_at  timestamptz default now();
alter table public.daizu_favorites add column if not exists category    text default 'cafe';
alter table public.daizu_favorites add column if not exists strength    text;
alter table public.daizu_favorites add column if not exists quantity    integer default 1;
alter table public.daizu_favorites add column if not exists spirit      text;
alter table public.daizu_favorites add column if not exists mixer       text;
alter table public.daizu_favorites add column if not exists subcategory text;

-- daizu_out_of_stock
alter table public.daizu_out_of_stock add column if not exists category text;
alter table public.daizu_out_of_stock add column if not exists item_id  text;


-- ---------------------------------------------------------------------
-- 6. DEFAULTS (match live exactly)
-- ---------------------------------------------------------------------

alter table public.daizu_orders alter column customer   set default 'Dez';
alter table public.daizu_orders alter column syrups     set default '{}';
alter table public.daizu_orders alter column sweetness  set default 'normal';
alter table public.daizu_orders alter column extras     set default '{}';
alter table public.daizu_orders alter column notes      set default '';
alter table public.daizu_orders alter column status     set default 'received';
alter table public.daizu_orders alter column created_at set default now();
alter table public.daizu_orders alter column category   set default 'cafe';
alter table public.daizu_orders alter column quantity   set default 1;

alter table public.daizu_favorites alter column syrups     set default '{}';
alter table public.daizu_favorites alter column sweetness  set default 'normal';
alter table public.daizu_favorites alter column extras     set default '{}';
alter table public.daizu_favorites alter column notes      set default '';
alter table public.daizu_favorites alter column customer   set default 'Dez';
alter table public.daizu_favorites alter column created_at set default now();
alter table public.daizu_favorites alter column category   set default 'cafe';
alter table public.daizu_favorites alter column quantity   set default 1;


-- ---------------------------------------------------------------------
-- 7. NOT NULL constraints (match live)
--    Applied only where the existing data permits, so this is safe and
--    idempotent against any table state.
-- ---------------------------------------------------------------------

do $$
declare
  spec      text;
  tbl       text;
  col       text;
  has_nulls boolean;
begin
  foreach spec in array array[
    'daizu_orders.customer',
    'daizu_orders.drink',
    'daizu_orders.syrups',
    'daizu_orders.extras',
    'daizu_orders.status',
    'daizu_orders.created_at',
    'daizu_orders.category',
    'daizu_orders.quantity',
    'daizu_favorites.label',
    'daizu_favorites.drink',
    'daizu_favorites.syrups',
    'daizu_favorites.extras',
    'daizu_favorites.created_at',
    'daizu_favorites.category',
    'daizu_favorites.quantity',
    'daizu_out_of_stock.category',
    'daizu_out_of_stock.item_id'
  ]
  loop
    tbl := split_part(spec, '.', 1);
    col := split_part(spec, '.', 2);
    execute format('select exists (select 1 from public.%I where %I is null)', tbl, col)
      into has_nulls;
    if not has_nulls then
      execute format('alter table public.%I alter column %I set not null', tbl, col);
    end if;
  end loop;
end $$;


-- ---------------------------------------------------------------------
-- 8. CHECK CONSTRAINTS
--    Postgres has no "add constraint if not exists", so each constraint is
--    dropped-if-exists and re-added. This is idempotent and touches no
--    data; it is the same pattern the older migration_bar.sql used.
--    Constraint names match live (mostly pre-rename legacy names).
-- ---------------------------------------------------------------------

-- daizu_orders
alter table public.daizu_orders drop constraint if exists orders_temp_check;
alter table public.daizu_orders add constraint orders_temp_check
  check (temp is null or temp in ('hot', 'iced'));

alter table public.daizu_orders drop constraint if exists orders_status_check;
alter table public.daizu_orders add constraint orders_status_check
  check (status in ('received', 'brewing', 'ready', 'cancelled'));

alter table public.daizu_orders drop constraint if exists orders_category_check;
alter table public.daizu_orders add constraint orders_category_check
  check (category in ('cafe', 'bar'));

alter table public.daizu_orders drop constraint if exists orders_strength_check;
alter table public.daizu_orders add constraint orders_strength_check
  check (strength is null or strength in ('light', 'standard', 'strong'));

alter table public.daizu_orders drop constraint if exists orders_quantity_check;
alter table public.daizu_orders add constraint orders_quantity_check
  check (quantity >= 1 and quantity <= 4);

alter table public.daizu_orders drop constraint if exists daizu_orders_subcategory_check;
alter table public.daizu_orders add constraint daizu_orders_subcategory_check
  check (subcategory is null or subcategory in ('cocktail', 'bottle'));

-- daizu_favorites
alter table public.daizu_favorites drop constraint if exists favorites_temp_check;
alter table public.daizu_favorites add constraint favorites_temp_check
  check (temp is null or temp in ('hot', 'iced'));

alter table public.daizu_favorites drop constraint if exists favorites_category_check;
alter table public.daizu_favorites add constraint favorites_category_check
  check (category in ('cafe', 'bar'));

alter table public.daizu_favorites drop constraint if exists favorites_strength_check;
alter table public.daizu_favorites add constraint favorites_strength_check
  check (strength is null or strength in ('light', 'standard', 'strong'));

alter table public.daizu_favorites drop constraint if exists favorites_quantity_check;
alter table public.daizu_favorites add constraint favorites_quantity_check
  check (quantity >= 1 and quantity <= 4);

alter table public.daizu_favorites drop constraint if exists daizu_favorites_subcategory_check;
alter table public.daizu_favorites add constraint daizu_favorites_subcategory_check
  check (subcategory is null or subcategory in ('cocktail', 'bottle'));

-- daizu_out_of_stock
alter table public.daizu_out_of_stock drop constraint if exists out_of_stock_category_check;
alter table public.daizu_out_of_stock add constraint out_of_stock_category_check
  check (category in ('drinks', 'milks', 'syrups'));

-- Note: there is deliberately NO check constraint on `mixer` live — it is a
-- free-text column. Reproduced as-is.


-- ---------------------------------------------------------------------
-- 9. INDEXES
--    (Primary key and unique indexes are created by their constraints
--    in sections 2-4; only the plain secondary indexes are listed here.)
-- ---------------------------------------------------------------------

create index if not exists orders_status_idx     on public.daizu_orders (status);
create index if not exists orders_created_at_idx on public.daizu_orders (created_at desc);
create index if not exists orders_category_idx   on public.daizu_orders (category);

-- daizu_favorites and daizu_out_of_stock have no secondary indexes live.


-- ---------------------------------------------------------------------
-- 10. ROW LEVEL SECURITY
--     SELECT-only public policies. No insert/update/delete policies —
--     writes must go through service-role API routes.
-- ---------------------------------------------------------------------

alter table public.daizu_orders        enable row level security;
alter table public.daizu_favorites     enable row level security;
alter table public.daizu_out_of_stock  enable row level security;

drop policy if exists "public_read_orders" on public.daizu_orders;
create policy "public_read_orders"
  on public.daizu_orders
  for select
  to public
  using (true);

drop policy if exists "public_read_favorites" on public.daizu_favorites;
create policy "public_read_favorites"
  on public.daizu_favorites
  for select
  to public
  using (true);

drop policy if exists "public_read_out_of_stock" on public.daizu_out_of_stock;
create policy "public_read_out_of_stock"
  on public.daizu_out_of_stock
  for select
  to public
  using (true);

-- =====================================================================
